In [2]:
import numpy as np

In [7]:
x = np.array([[5, 1, -2, 0], [0, 3, 4, 3], [2, 3, 1, 1]])

In [8]:
y = np.array([[1, -3], [2, -2], [3, -1], [0, 0]])

In [10]:
m =np.dot(x, y)

In [11]:
m.sum()

-8

In [32]:
def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param first: list of "size" lists, each contains "size" floats
    """

    #YOUR CODE: please do not use numpy
    zip_second = list(zip(*second))   
    result = [[sum(ec * er  for ec, er in zip(c_second, r_first)) for c_second in zip_second] for r_first in first]
    return result

def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """

    #YOUR CODE: please use numpy

    result = np.dot(first, second)
    return result

In [33]:
x = [[1, 2], [3, 4]]

In [34]:
y = [[5, 6], [7, 8]]

In [35]:
xn = np.array(x)

In [36]:
yn = np.array(y)

In [37]:
numpy_mult(xn, yn)

array([[19, 22],
       [43, 50]])

In [38]:
no_numpy_mult(x, y)

[[19, 22], [43, 50]]

In [45]:
def no_numpy_scalar(v1, v2):
    #YOUR CODE: please do not use numpy

    result = sum([ev1 * ev2 for ev1, ev2 in zip(v1, v2)])
    return result

def numpy_scalar (v1, v2):
    #YOUR CODE

    result = np.dot(v1, v2)
    return result

In [46]:
v1 = [1, 2, 3]

In [47]:
v2 = [4, 5, 6]

In [48]:
numpy_scalar(v1, v2)

32

In [49]:
no_numpy_scalar(v1, v2)

32

In [59]:
def diag_2k(a):
    #YOUR CODE
    d = np.diagonal(a)
    result = d[d%2 == 0].sum()
    return result

In [60]:
a = np.array([[2, 1, 3], [3, 5, 6], [4, 9, 8]])

In [61]:
a

array([[2, 1, 3],
       [3, 5, 6],
       [4, 9, 8]])

In [62]:
diag_2k(a)

10

In [67]:
def cumsum(A):
    #YOUR CODE

    result = np.cumsum(A, axis=1) 
    return result

In [68]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [69]:
cumsum(A)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [158]:
def encode(a):
    m = np.append(np.append(True, a[:-1] !=a [1:]), True)
    idx = np.flatnonzero(m)
    values = a[idx[:-1]]
    counts = np.diff(idx)
    return values, counts

In [159]:
# encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3], np.array[1, 2, 2, 2, 2, 1, 2])

In [160]:
a = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [161]:
encode(a)

(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2], dtype=int64))

In [198]:
def transform(X, a=1):
    """
    param X: np.array[batch_size, n]
    """
    Y = X.copy()
    Y[:, 1::2] = a
    Y[:, 0::2] = Y[:, 0::2]**3
    return np.hstack((X, Y[:, ::-1]))

In [199]:
X = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])

In [200]:
transform(X, a=10)

array([[  1,   2,   3,   4,   5, 125,  10,  27,  10,   1],
       [  2,   3,   4,   5,   6, 216,  10,  64,  10,   8]])